import type { ActionDefinition } from "./baseActions";

export const playerExpandActions: ActionDefinition[] = [
  {
    id: "two-player-flex",
    name: "两人扩展行动",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["四选一：小树林、朴素生孩子、资源市场、动物市场。", "小树林：每回合累积1木材，执行时拿走全部木材。", "朴素生孩子：第5回合后，且有空房间时新增1家庭成员。", "资源市场：获得1石头和1食物。", "动物市场：三选一，获得羊和食物、获得野猪、或支付食物获得牛。"],
    restrictions: ["只能被一个工人使用"],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { id: "copse", label: "小树林", description: "拿走此格累积的全部木材。", type: "takeAccumulated" },
          { id: "modest-wish-for-children", label: "朴素生孩子", description: "第5回合后，且有空房间时新增1家庭成员。", type: "familyGrowth", requiresRoom: true, minimumRound: 5 },
          { id: "resource-market", label: "资源市场", description: "获得1石头和1食物。", type: "buildingSupplies", resources: { stone: 1, food: 1 } },
          {
            id: "animal-market",
            label: "动物市场",
            description: "三选一：羊和食物、野猪、或牛并支付食物。",
            type: "chooseOne",
            effects: [
              { id: "animal-market-sheep", label: "羊和食物", description: "获得1只羊，并获得1个食物。", type: "gainAnimal", animal: "sheep", amount: 1, foodDelta: 1 },
              { id: "animal-market-boar", label: "野猪", description: "获得1只野猪。", type: "gainAnimal", animal: "boar", amount: 1 },
              { id: "animal-market-cattle", label: "牛并支付食物", description: "支付1个食物，获得1头牛。", type: "gainAnimal", animal: "cattle", amount: 1, foodDelta: -1 },
            ],
          },
        ],
      },
    ],
    playerCounts: [2, 3, 4, 5, 6],
    replenish: { wood: 1 },
  },
  {
    id: "three-four-flex",
    name: "三四人扩展行动",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["二选一：动物市场、朴素生孩子。", "动物市场：三选一，获得羊和食物、获得野猪、或获得牛并支付食物。", "朴素生孩子：第5回合后，且有空房间时新增1家庭成员。"],
    restrictions: ["只能被一个工人使用"],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          {
            id: "animal-market",
            label: "动物市场",
            description: "三选一：羊和食物、野猪、或牛并支付食物。",
            type: "chooseOne",
            effects: [
              { id: "animal-market-sheep", label: "羊和食物", description: "获得1只羊，并获得1个食物。", type: "gainAnimal", animal: "sheep", amount: 1, foodDelta: 1 },
              { id: "animal-market-boar", label: "野猪", description: "获得1只野猪。", type: "gainAnimal", animal: "boar", amount: 1 },
              { id: "animal-market-cattle", label: "牛并支付食物", description: "支付1个食物，获得1头牛。", type: "gainAnimal", animal: "cattle", amount: 1, foodDelta: -1 },
            ],
          },
          { id: "modest-wish-for-children", label: "朴素生孩子", description: "第5回合后，且有空房间时新增1家庭成员。", type: "familyGrowth", requiresRoom: true, minimumRound: 5 },
        ],
      },
    ],
    playerCounts: [3, 4, 5, 6],
    replenish: {},
  },
  {
    id: "five-lessons-copse",
    name: "课程 / 小树林",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["二选一：打出职业卡，或拿走小树林累积的全部木材。", "小树林每回合累积1木材。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "playOccupation", label: "打出职业卡", description: "从手牌选择1张职业卡打出。" },
          { type: "takeAccumulated", label: "小树林", description: "拿走此格累积的全部木材。" },
        ],
      },
    ],
    playerCounts: [5, 6],
    replenish: { wood: 1 },
  },
  {
    id: "five-grove",
    name: "树林",
    type: "accumulation",
    cost: {},
    gain: { wood: 2 },
    prerequisites: [],
    rules: ["每回合增加2木头", "拿走所有木头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: [5, 6],
    replenish: { wood: 2 },
  },
  {
    id: "five-riverbank-forest",
    name: "河岸林",
    type: "accumulation",
    cost: {},
    gain: { wood: 1, reed: 1 },
    prerequisites: [],
    rules: ["每回合增加1木头和1芦苇", "拿走所有资源"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: [5, 6],
    replenish: { wood: 1, reed: 1 },
  },
  {
    id: "five-lessons-family",
    name: "课程 / 朴素生孩子",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["二选一：打出职业卡，或朴素生孩子。", "朴素生孩子：第5回合后，且有空房间时新增1家庭成员。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "playOccupation", label: "打出职业卡", description: "从手牌选择1张职业卡打出。" },
          { type: "familyGrowth", label: "朴素生孩子", description: "第5回合后，且有空房间时新增1家庭成员。", requiresRoom: true, minimumRound: 5 },
        ],
      },
    ],
    playerCounts: [5, 6],
    replenish: {},
  },
  {
    id: "five-animal-market",
    name: "动物市场",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["三选一：获得羊和食物、获得野猪、或获得牛并支付食物。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { id: "animal-market-sheep", label: "羊和食物", description: "获得1只羊，并获得1个食物。", type: "gainAnimal", animal: "sheep", amount: 1, foodDelta: 1 },
          { id: "animal-market-boar", label: "野猪", description: "获得1只野猪。", type: "gainAnimal", animal: "boar", amount: 1 },
          { id: "animal-market-cattle", label: "牛并支付食物", description: "支付1个食物，获得1头牛。", type: "gainAnimal", animal: "cattle", amount: 1, foodDelta: -1 },
        ],
      },
    ],
    playerCounts: [5, 6],
    replenish: {},
  },
  {
    id: "five-resource-market",
    name: "资源市场",
    type: "instant",
    cost: {},
    gain: { reed: 1, stone: 1, wood: 1 },
    prerequisites: [],
    rules: ["获得1芦苇、1石头、1木头"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      { type: "gainResource", resource: "reed", amount: 1 },
      { type: "gainResource", resource: "stone", amount: 1 },
      { type: "gainResource", resource: "wood", amount: 1 },
    ],
    playerCounts: [5, 6],
    replenish: {},
  },
  {
    id: "five-hollow",
    name: "黏土洼地",
    type: "accumulation",
    cost: {},
    gain: { clay: 3 },
    prerequisites: [],
    rules: ["每回合增加3砖头", "拿走所有砖头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: [5, 6],
    replenish: { clay: 3 },
  },
  {
    id: "five-build-room-traveling",
    name: "建房间 / 巡回艺人",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["二选一：建房间，或拿走巡回艺人累积的全部食物。", "建房间：新房间必须与已有房间正交相邻，一次可建多个。", "巡回艺人每回合累积1食物。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "buildRooms", label: "建房间", description: "新房间必须与已有房间正交相邻；一次可建多个。" },
          { type: "takeAccumulated", label: "巡回艺人", description: "拿走此格累积的全部食物。" },
        ],
      },
    ],
    playerCounts: [5, 6],
    replenish: { food: 1 },
  },
  {
    id: "six-farming-supplies",
    name: "农耕补给",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可用1食物换1谷物，可重复。", "可用1食物翻耕1块田，可重复。", "也可两者都执行。"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "farmingSupplies", label: "农耕补给", description: "用食物换谷物，或用食物翻田，也可两者都执行。" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-building-supplies",
    name: "建筑补给",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["获得1个芦苇或石头。", "获得1个木材或黏土。", "获得1个食物。"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "buildingSupplies", label: "建筑补给", description: "选择1个芦苇或石头、1个木材或黏土，并获得1个食物。" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-corral",
    name: "畜栏",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["增加1只自己还没有的动物。", "例如已有羊时，可在野猪和牛中选1只。"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "gainMissingAnimal", label: "增加缺少的动物", description: "选择1只自己还没有的动物，并安排到合法空间。" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-side-job",
    name: "副业",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可花费1木材建造1个马厩。", "可烤面包。", "也可两者都执行。"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "sideJob", label: "副业", description: "花费1木材建造1个马厩，或烤面包，也可两者都执行。" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-improvement",
    name: "设施",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["二选一：打出小设施，或第5回合后购买大设施。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "playMinorImprovement", label: "打出小设施", description: "从手牌选择1张小设施打出。" },
          { type: "buyMajorImprovement", label: "购买大设施", description: "第5回合后，支付资源购买1张大设施。", minimumRound: 5 },
        ],
      },
    ],
    playerCounts: [6],
    replenish: {},
  },
];
