import type { ActionDefinition } from "./baseActions";

export const playerExpandActions: ActionDefinition[] = [
  {
    id: "two-player-flex",
    name: "两人扩展行动",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["Copse", "Modest wish for children", "Resource Market", "Animal Market 四选一"],
    restrictions: ["只能被一个工人使用"],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "takeAccumulated" },
          { type: "familyGrowth", requiresRoom: true, minimumRound: 5 },
          { type: "buildingSupplies" },
          { type: "gainAnimal", animal: "sheep", amount: 1 },
          { type: "gainAnimal", animal: "boar", amount: 1 },
          { type: "gainAnimal", animal: "cattle", amount: 1 },
        ],
      },
    ],
    playerCounts: [2, 3, 4, 5, 6],
    replenish: { wood: 1 },
  },
  {
    id: "three-four-flex",
    name: "三四人扩展行动",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["Animal Market", "Modest wish for children 二选一"],
    restrictions: ["只能被一个工人使用"],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "gainAnimal", animal: "sheep", amount: 1 },
          { type: "gainAnimal", animal: "boar", amount: 1 },
          { type: "gainAnimal", animal: "cattle", amount: 1 },
          { type: "familyGrowth", requiresRoom: true, minimumRound: 5 },
        ],
      },
    ],
    playerCounts: [3, 4, 5, 6],
    replenish: {},
  },
  {
    id: "five-lessons-copse",
    name: "课程 / Copse",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["课程费用2食物", "或每回合增加1木头并拿走所有木头"],
    restrictions: ["职业卡内容未来开放"],
    occupiedBy: null,
    effects: [{ type: "chooseOne", effects: [{ type: "playOccupationPlaceholder" }, { type: "takeAccumulated" }] }],
    playerCounts: [5, 6],
    replenish: { wood: 1 },
  },
  {
    id: "five-grove",
    name: "Grove",
    type: "accumulation",
    cost: {},
    gain: { wood: 2 },
    prerequisites: [],
    rules: ["每回合增加2木头", "拿走所有木头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: [5, 6],
    replenish: { wood: 2 },
  },
  {
    id: "five-riverbank-forest",
    name: "RiverBank Forest",
    type: "accumulation",
    cost: {},
    gain: { wood: 1, reed: 1 },
    prerequisites: [],
    rules: ["每回合增加1木头和1芦苇", "拿走所有资源"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: [5, 6],
    replenish: { wood: 1, reed: 1 },
  },
  {
    id: "five-lessons-family",
    name: "课程 / Modest wish for children",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["课程", "或第5回合后且有空房时新增1家庭成员"],
    restrictions: ["职业卡内容未来开放"],
    occupiedBy: null,
    effects: [{ type: "chooseOne", effects: [{ type: "playOccupationPlaceholder" }, { type: "familyGrowth", requiresRoom: true, minimumRound: 5 }] }],
    playerCounts: [5, 6],
    replenish: {},
  },
  {
    id: "five-animal-market",
    name: "Animal Market",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["获得羊+粮食", "获得猪", "获得牛+丢掉粮食"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "chooseOne", effects: [{ type: "gainAnimal", animal: "sheep", amount: 1 }, { type: "gainAnimal", animal: "boar", amount: 1 }, { type: "gainAnimal", animal: "cattle", amount: 1 }] }],
    playerCounts: [5, 6],
    replenish: {},
  },
  {
    id: "five-resource-market",
    name: "Resource Market",
    type: "instant",
    cost: {},
    gain: { reed: 1, stone: 1, wood: 1 },
    prerequisites: [],
    rules: ["获得1芦苇、1石头、1木头"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      { type: "gainResource", resource: "reed", amount: 1 },
      { type: "gainResource", resource: "stone", amount: 1 },
      { type: "gainResource", resource: "wood", amount: 1 },
    ],
    playerCounts: [5, 6],
    replenish: {},
  },
  {
    id: "five-hollow",
    name: "Hollow",
    type: "accumulation",
    cost: {},
    gain: { clay: 3 },
    prerequisites: [],
    rules: ["每回合增加3砖头", "拿走所有砖头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: [5, 6],
    replenish: { clay: 3 },
  },
  {
    id: "five-build-room-traveling",
    name: "建房间 / Traveling Players",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["建房间", "或每回合增加1粮食并拿走所有粮食"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "chooseOne", effects: [{ type: "buildRooms" }, { type: "takeAccumulated" }] }],
    playerCounts: [5, 6],
    replenish: { food: 1 },
  },
  {
    id: "six-farming-supplies",
    name: "Farming Supplies",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可1食物换1小麦", "可1食物耕种1块田", "可两者一起执行"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "farmingSupplies" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-building-supplies",
    name: "Builing Supplies",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["获得芦苇或石头", "木头或砖头", "一个粮食"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "buildingSupplies" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-corral",
    name: "corral",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可增加一只没有的动物", "如已有羊，可在猪和牛中选一只"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "gainMissingAnimal" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-side-job",
    name: "side job",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可花费1木头建筑1马厩", "可烤面包", "可两者一起执行"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "sideJob" }],
    playerCounts: [6],
    replenish: {},
  },
  {
    id: "six-improvement",
    name: "Improvement",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["打出次要发展卡", "或第5回合后购买主要发展卡"],
    restrictions: ["次要发展卡内容未来开放"],
    occupiedBy: null,
    effects: [{ type: "chooseOne", effects: [{ type: "playMinorImprovementPlaceholder" }, { type: "buyMajorImprovement" }] }],
    playerCounts: [6],
    replenish: {},
  },
];
