import type { CardState } from "../state/CardState";
import type { ActionDefinition } from "./baseActions";

export const roundCards: CardState[] = [
  { id: "major-minor-improvement", name: "主要/次要发展卡", type: "round" },
  { id: "fencing", name: "围栏", type: "round" },
  { id: "sow-bake", name: "播种与烤面包", type: "round" },
  { id: "sheep-market", name: "羊市场", type: "round" },
  { id: "house-redevelopment", name: "房屋翻修", type: "round" },
  { id: "western-quarry", name: "西部采石场", type: "round" },
  { id: "family-growth-room", name: "生孩子（需要空房）", type: "round" },
  { id: "vegetable-seeds", name: "蔬菜种子", type: "round" },
  { id: "boar-market", name: "野猪市场", type: "round" },
  { id: "eastern-quarry", name: "东部采石场", type: "round" },
  { id: "cattle-market", name: "牛市场", type: "round" },
  { id: "cultivation", name: "耕种", type: "round" },
  { id: "family-growth-any", name: "紧急生孩子（不需要空房）", type: "round" },
  { id: "farm-redevelopment", name: "最终翻修", type: "round" },
];

const allPlayerCounts = [1, 2, 3, 4, 5, 6];

export const roundActionDefinitions: ActionDefinition[] = [
  {
    id: "major-minor-improvement",
    name: "主要/次要发展卡",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["购买主要发展卡", "或打出次要发展卡"],
    restrictions: ["次要发展卡内容未来开放"],
    occupiedBy: null,
    effects: [{ type: "chooseOne", effects: [{ type: "buyMajorImprovement" }, { type: "playMinorImprovementPlaceholder" }] }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 1,
  },
  {
    id: "fencing",
    name: "围栏",
    type: "instant",
    cost: { wood: 1 },
    gain: {},
    prerequisites: [],
    rules: ["建造任意数量围栏", "必须形成完全封闭区域", "形成后得到牧场", "牧场必须连续"],
    restrictions: ["动物种类不可混养"],
    occupiedBy: null,
    effects: [{ type: "buildFences" }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 1,
  },
  {
    id: "sow-bake",
    name: "播种与烤面包",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可播种", "可烤面包", "可两者都执行"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "chooseAny", effects: [{ type: "sow" }, { type: "bakeBread" }] }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 1,
  },
  {
    id: "sheep-market",
    name: "羊市场",
    type: "accumulation",
    cost: {},
    gain: { sheep: 1 },
    prerequisites: ["必须有地方饲养"],
    rules: ["每轮补充1羊", "获得全部羊"],
    restrictions: ["超过容量的羊可丢弃或通过主要发展卡做成食物"],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { sheep: 1 },
    season: 1,
  },
  {
    id: "house-redevelopment",
    name: "房屋翻修",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: ["所有房屋必须一起翻修"],
    rules: ["先翻修房屋", "然后购买主要发展卡"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "renovate", allowMajorImprovement: true }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 2,
  },
  {
    id: "western-quarry",
    name: "西部采石场",
    type: "accumulation",
    cost: {},
    gain: { stone: 1 },
    prerequisites: [],
    rules: ["每轮补充1石头", "获得全部石头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { stone: 1 },
    season: 2,
  },
  {
    id: "family-growth-room",
    name: "生孩子（需要空房）",
    type: "instant",
    cost: {},
    gain: {},
    prerequisites: ["空房间数量 >= 1"],
    rules: ["新增1家庭成员", "新成员下轮开始可行动"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "familyGrowth", requiresRoom: true }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 2,
  },
  {
    id: "vegetable-seeds",
    name: "蔬菜种子",
    type: "instant",
    cost: {},
    gain: { vegetable: 1 },
    prerequisites: [],
    rules: ["获得1蔬菜"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "gainResource", resource: "vegetable", amount: 1 }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 3,
  },
  {
    id: "boar-market",
    name: "野猪市场",
    type: "accumulation",
    cost: {},
    gain: { boar: 1 },
    prerequisites: ["必须有地方饲养"],
    rules: ["每轮补充1野猪", "获得全部野猪"],
    restrictions: ["超过容量的野猪可丢弃或通过主要发展卡做成食物"],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { boar: 1 },
    season: 3,
  },
  {
    id: "eastern-quarry",
    name: "东部采石场",
    type: "accumulation",
    cost: {},
    gain: { stone: 1 },
    prerequisites: [],
    rules: ["每轮补充1石头", "获得全部石头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { stone: 1 },
    season: 4,
  },
  {
    id: "cattle-market",
    name: "牛市场",
    type: "accumulation",
    cost: {},
    gain: { cattle: 1 },
    prerequisites: ["必须有地方饲养"],
    rules: ["每轮补充1牛", "获得全部牛"],
    restrictions: ["超过容量的牛可丢弃或通过主要发展卡做成食物"],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { cattle: 1 },
    season: 4,
  },
  {
    id: "cultivation",
    name: "耕种",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["翻耕1块田", "并且/或者播种"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "chooseAny", effects: [{ type: "plowField" }, { type: "sow" }] }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 5,
  },
  {
    id: "family-growth-any",
    name: "紧急生孩子（不需要空房）",
    type: "instant",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["新增1家庭成员", "新成员下轮开始可行动"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "familyGrowth", requiresRoom: false }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 5,
  },
  {
    id: "farm-redevelopment",
    name: "最终翻修",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["翻修房屋", "建造围栏"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "chooseAny", effects: [{ type: "renovate", allowMajorImprovement: false }, { type: "buildFences" }] }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 6,
  },
];
