import type { CardState } from "../state/CardState";
import type { ActionDefinition } from "./baseActions";

export const roundCards: CardState[] = [
  { id: "major-minor-improvement", name: "大设施 / 小设施", type: "round" },
  { id: "fencing", name: "围栏", type: "round" },
  { id: "sow-bake", name: "播种与烤面包", type: "round" },
  { id: "sheep-market", name: "羊市场", type: "round" },
  { id: "house-redevelopment", name: "房屋翻修", type: "round" },
  { id: "western-quarry", name: "西部采石场", type: "round" },
  { id: "family-growth-room", name: "生孩子（需要空房）", type: "round" },
  { id: "vegetable-seeds", name: "蔬菜种子", type: "round" },
  { id: "boar-market", name: "野猪市场", type: "round" },
  { id: "eastern-quarry", name: "东部采石场", type: "round" },
  { id: "cattle-market", name: "牛市场", type: "round" },
  { id: "cultivation", name: "耕种", type: "round" },
  { id: "family-growth-any", name: "紧急生孩子（不需要空房）", type: "round" },
  { id: "farm-redevelopment", name: "最终翻修", type: "round" },
];

const allPlayerCounts = [1, 2, 3, 4, 5, 6];

export const roundActionDefinitions: ActionDefinition[] = [
  {
    id: "major-minor-improvement",
    name: "大设施 / 小设施",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["二选一：购买大设施，或打出小设施。", "当前版本小设施暂未开放，但大设施仍可购买。"],
    restrictions: ["小设施内容未来开放"],
    occupiedBy: null,
    effects: [
      {
        type: "chooseOne",
        effects: [
          { type: "buyMajorImprovement", label: "购买大设施", description: "支付对应资源，获得一张未被购买的大设施。" },
          { type: "playMinorImprovementPlaceholder", label: "打出小设施", description: "小设施将在后续版本开放。" },
        ],
      },
    ],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 1,
  },
  {
    id: "fencing",
    name: "围栏",
    type: "instant",
    cost: { wood: 1 },
    gain: {},
    prerequisites: [],
    rules: ["建造任意数量围栏，每段消耗1木材。", "围栏必须形成完全封闭区域，形成后得到连续牧场。", "牧场内动物不可混养。"],
    restrictions: ["动物种类不可混养"],
    occupiedBy: null,
    effects: [{ type: "buildFences", label: "建围栏", description: "逐段选择围栏；每段消耗1木材，必须形成封闭牧场。" }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 1,
  },
  {
    id: "sow-bake",
    name: "播种与烤面包",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可播种。", "可烤面包。", "也可两者都执行。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseAny",
        effects: [
          { type: "sow", label: "播种", description: "在空田中播种谷物或蔬菜；可以只播一部分。" },
          { type: "bakeBread", label: "烤面包", description: "需要拥有可烤面包的大设施。" },
        ],
      },
    ],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 1,
  },
  {
    id: "sheep-market",
    name: "羊市场",
    type: "accumulation",
    cost: {},
    gain: { sheep: 1 },
    prerequisites: ["必须有地方饲养"],
    rules: ["每轮补充1羊", "获得全部羊"],
    restrictions: ["超过容量的羊可丢弃或通过大设施做成食物"],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { sheep: 1 },
    season: 1,
  },
  {
    id: "house-redevelopment",
    name: "房屋翻修",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: ["所有房屋必须一起翻修"],
    rules: ["必须先翻修房屋，翻修后可选择购买大设施或打出小设施。", "所有房屋必须一次全部翻修。", "木屋翻成黏土屋：每间1黏土，额外1芦苇。", "黏土屋翻成石屋：每间1石头，额外1芦苇。", "当前版本小设施暂未开放。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseAny",
        effects: [
          { type: "renovate", id: "redevelop-renovate", label: "翻修房屋", description: "所有房屋必须一次全部翻修。", allowMajorImprovement: false },
          { type: "buyMajorImprovement", id: "redevelop-major", label: "购买大设施", description: "必须先完成翻修，随后支付资源购买1张大设施。", requiresSelectedEffectTypes: ["renovate"] },
          { type: "playMinorImprovementPlaceholder", id: "redevelop-minor", label: "打出小设施", description: "必须先完成翻修；小设施将在后续版本开放。", requiresSelectedEffectTypes: ["renovate"] },
        ],
      },
    ],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 2,
  },
  {
    id: "western-quarry",
    name: "西部采石场",
    type: "accumulation",
    cost: {},
    gain: { stone: 1 },
    prerequisites: [],
    rules: ["每轮补充1石头", "获得全部石头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { stone: 1 },
    season: 2,
  },
  {
    id: "family-growth-room",
    name: "生孩子（需要空房）",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: ["空房间数量 >= 1"],
    rules: ["必须先新增1家庭成员。", "新成员下轮开始可行动。", "之后可打出1张小设施；当前版本小设施暂未开放。"],
    restrictions: ["小设施内容未来开放"],
    occupiedBy: null,
    effects: [
      {
        type: "chooseAny",
        effects: [
          { type: "familyGrowth", id: "family-growth-room", label: "生孩子", description: "需要至少1个空房间；新成员下轮开始可行动。", requiresRoom: true },
          { type: "playMinorImprovementPlaceholder", id: "family-growth-minor", label: "打出小设施", description: "必须先生孩子；小设施将在后续版本开放。", requiresSelectedEffectTypes: ["familyGrowth"] },
        ],
      },
    ],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 2,
  },
  {
    id: "vegetable-seeds",
    name: "蔬菜种子",
    type: "instant",
    cost: {},
    gain: { vegetable: 1 },
    prerequisites: [],
    rules: ["获得1蔬菜"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "gainResource", resource: "vegetable", amount: 1 }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 3,
  },
  {
    id: "boar-market",
    name: "野猪市场",
    type: "accumulation",
    cost: {},
    gain: { boar: 1 },
    prerequisites: ["必须有地方饲养"],
    rules: ["每轮补充1野猪", "获得全部野猪"],
    restrictions: ["超过容量的野猪可丢弃或通过大设施做成食物"],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { boar: 1 },
    season: 3,
  },
  {
    id: "eastern-quarry",
    name: "东部采石场",
    type: "accumulation",
    cost: {},
    gain: { stone: 1 },
    prerequisites: [],
    rules: ["每轮补充1石头", "获得全部石头"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { stone: 1 },
    season: 4,
  },
  {
    id: "cattle-market",
    name: "牛市场",
    type: "accumulation",
    cost: {},
    gain: { cattle: 1 },
    prerequisites: ["必须有地方饲养"],
    rules: ["每轮补充1牛", "获得全部牛"],
    restrictions: ["超过容量的牛可丢弃或通过大设施做成食物"],
    occupiedBy: null,
    effects: [{ type: "takeAccumulated" }],
    playerCounts: allPlayerCounts,
    replenish: { cattle: 1 },
    season: 4,
  },
  {
    id: "cultivation",
    name: "耕种",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["可翻耕1块田。", "可播种。", "也可两者都执行。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseAny",
        effects: [
          { type: "plowField", label: "翻田", description: "选择1块合法空地翻成田地。" },
          { type: "sow", label: "播种", description: "在空田中播种谷物或蔬菜；可以只播一部分。" },
        ],
      },
    ],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 5,
  },
  {
    id: "family-growth-any",
    name: "紧急生孩子（不需要空房）",
    type: "instant",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["新增1家庭成员", "新成员下轮开始可行动"],
    restrictions: [],
    occupiedBy: null,
    effects: [{ type: "familyGrowth", requiresRoom: false }],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 5,
  },
  {
    id: "farm-redevelopment",
    name: "最终翻修",
    type: "choice",
    cost: {},
    gain: {},
    prerequisites: [],
    rules: ["必须先翻修房屋，翻修后可建造围栏。", "所有房屋必须一次全部翻修。", "木屋翻成黏土屋：每间1黏土，额外1芦苇。", "黏土屋翻成石屋：每间1石头，额外1芦苇。"],
    restrictions: [],
    occupiedBy: null,
    effects: [
      {
        type: "chooseAny",
        effects: [
          { type: "renovate", label: "翻修房屋", description: "所有房屋必须一起翻修。", allowMajorImprovement: false },
          { type: "buildFences", label: "建围栏", description: "必须先完成翻修；逐段选择围栏，每段消耗1木材，必须形成封闭牧场。", requiresSelectedEffectTypes: ["renovate"] },
        ],
      },
    ],
    playerCounts: allPlayerCounts,
    replenish: {},
    season: 6,
  },
];
